---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.port: 5601
server.name: kibana
server.host: "0.0.0.0"

#server.ssl.enabled: true
#server.ssl.key: /usr/share/kibana/config/kibana.key
#server.ssl.certificate: /usr/share/kibana/config/kibana.crt

elasticsearch.url: "http://elasticsearch:9200"
