- pipeline.id: ddos
  queue.type: persisted
  path.config: "/usr/share/logstash/pipeline/ddos.conf"
  pipeline.workers: 1
#- pipeline.id: filebeat
#  queue.type: persisted
#  path.config: "/usr/share/logstash/pipeline/filebeat.conf"
#- pipeline.id: metricbeat
#  queue.type: persisted
#  path.config: "/usr/share/logstash/pipeline/metricbeat.conf"


